# Generated by Django 2.2.2 on 2019-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pactissueNo', models.CharField(max_length=32)),
                ('bidCash', models.IntegerField()),
                ('termMonth', models.IntegerField()),
                ('businessRate', models.CharField(max_length=64)),
                ('issueTime', models.DateTimeField()),
                ('xyLevel', models.CharField(max_length=8)),
                ('surplusMoney', models.CharField(max_length=32)),
                ('applyAmt', models.CharField(max_length=32)),
                ('bidPeopleNum', models.IntegerField()),
                ('returnMethod', models.CharField(max_length=32)),
                ('balance', models.CharField(max_length=32)),
                ('closedDay', models.CharField(max_length=32)),
                ('bidState', models.CharField(max_length=32)),
                ('bidAmt', models.CharField(max_length=32)),
                ('bidProgress', models.CharField(max_length=32)),
                ('applyTitle', models.CharField(max_length=32)),
            ],
        ),
    ]
